### ISSUE TITLE
Change airu ssid

### ISSUE THREAD

**Issue by ktingey** [ktingey/AirU#13]
For security reasons, we should only publish the last 4 characters of the SSID. 
 ie. AirU-FFFF

**Comment by tbec** [comment]
Will we be able to differentiate boards with the same ending mac addresses on the server side?

**Comment by ktingey** [comment]
The entire Mac address should be published.  Are any the same?

Kyle

**Comment by tbec** [comment]
Oh, it's for the SSID. Nevermind, I'm deleting these :D

**Comment by tbec** [comment]
Done
